const BLOG_POSTS : {key: number, title:string, content:string}[] = [
    {
        key: 0,
        title: "Why React is the coolest.",
        content: "Sed lectus ex, consectetur adipiscing elit. Aenean sodales est et euismod elementum. Aliquam id ultrices mi. Nulla finibus ornare porta. Cras convallis mauris metus, sit amet congue arcu consectetur quis. Nullam sodales egestas sodales. Quisque lacinia mauris eu turpis convallis consequat. Nunc lorem augue, placerat nec nulla at, tempus faucibus massa. Integer tempus molestie est blandit interdum. Suspendisse malesuada mauris nunc, ac pellentesque justo gravida quis. Curabitur eu sapien dictum, dignissim lectus in, ornare tortor. Fusce metus felis, porttitor vel vulputate in, hendrerit in tellus. Nunc tempor mattis tortor nec mollis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam viverra justo libero, id dignissim dui molestie quis. Vestibulum sed ante magna. Nulla vel hendrerit ligula, in scelerisque sapien. In velit sapien, egestas at aliquam quis, convallis vel sapien. Nulla in nunc quam. Integer consequat vestibulum dignissim. Maecenas sollicitudin viverra pharetra. Pellentesque magna felis, pretium lacinia lorem at, aliquet luctus nisl. Mauris in justo risus. Quisque egestas eget justo eu iaculis. In lacinia dapibus aliquet. In non tristique leo, a varius nisi. Nulla vitae tincidunt lectus. Donec varius enim elit, rhoncus aliquet quam tristique at. Fusce magna diam, mattis in pellentesque vitae, imperdiet nec felis. Fusce tristique magna ac volutpat rhoncus. Curabitur faucibus metus eu ligula lobortis aliquam. Quisque ut commodo justo. Donec ut enim cursus, sollicitudin est nec, placerat lectus."
    },
    {
        key: 1,
        title: "My experience owning two dozen cats.",
        content: "Vivamus vel posuere ipsum. Phasellus rutrum, sem in maximus condimentum, lorem ligula viverra sapien, at malesuada libero risus a massa. Duis sit amet tortor et diam viverra vestibulum quis a lectus. Aliquam nunc orci, iaculis sed est eu, aliquet molestie enim. Sed et scelerisque nibh, eget malesuada lorem. Nam libero nisi, porttitor sit amet elit a, maximus cursus quam. Nulla sagittis, eros vel mattis varius, sem turpis bibendum nisi, non finibus diam sem sed metus. Integer porttitor velit sed leo suscipit tincidunt. Quisque pellentesque pretium tincidunt. Ut eu quam luctus, iaculis elit ut, ullamcorper massa. In tempor nec eros eu dapibus. Praesent maximus, sapien id blandit pellentesque, nisi erat iaculis tortor, sed mollis ipsum lorem blandit lorem. Ut nec quam consequat, porttitor neque nec, eleifend ipsum. Nunc et urna quam. Morbi dignissim quam vel gravida rhoncus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque cursus ipsum ac eros consectetur rutrum. Maecenas maximus ullamcorper magna, vel aliquet nisi mollis tristique. Proin nec lacus et elit blandit ultricies vel eu tellus. Morbi et leo tincidunt, lacinia dolor ac, imperdiet tellus. Praesent rhoncus nunc porta justo tincidunt, vel varius justo hendrerit. Praesent congue, dui ultrices maximus aliquam, turpis lacus interdum est, sed malesuada ante metus et turpis. Pellentesque rutrum velit ipsum, elementum efficitur nibh ullamcorper nec. Aenean placerat ipsum non purus pretium, a blandit augue pretium. Vivamus lobortis sagittis bibendum."
    },
    {
        key: 2,
        title: "10k hours on League: This is my story.",
        content: " Curabitur sodales et enim at varius. In in nunc lectus. Duis tempus tristique ultricies. Ut congue neque purus, nec condimentum ligula semper eu. In sit amet erat enim. Integer fringilla tortor nec massa fringilla congue. Maecenas a ex arcu. Mauris blandit blandit mi pharetra vulputate. Nulla sit amet nunc vitae magna elementum mollis tristique vitae magna. Mauris ultrices felis at dolor gravida, fermentum pellentesque ligula consequat. Proin quam mi, tincidunt vitae turpis varius, vestibulum imperdiet lorem. Donec maximus dolor urna, eget consectetur erat euismod vel. Fusce fermentum tortor in purus iaculis scelerisque. Vivamus sollicitudin ligula id ipsum rhoncus, vel blandit sapien iaculis. Sed venenatis neque eu dui aliquam, eget egestas augue porttitor. Vivamus at ante nec augue hendrerit ullamcorper."
    }
]

export default BLOG_POSTS;